Document: noteshrink-gui
Title: Debian noteshrink-gui Manual
Author: <insert document author here>
Abstract: This manual describes what noteshrink-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/noteshrink-gui/noteshrink-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/noteshrink-gui/noteshrink-gui.ps.gz

Format: text
Files: /usr/share/doc/noteshrink-gui/noteshrink-gui.text.gz

Format: HTML
Index: /usr/share/doc/noteshrink-gui/html/index.html
Files: /usr/share/doc/noteshrink-gui/html/*.html
